[editor]
mouse = false
line-number = "relative"
cursorline = true
true-color = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = [ "mode", "spinner", "separator", "spacer", "version-control", "read-only-indicator", "file-modification-indicator" ]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "VISUAL"


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"


[editor.auto-pairs]
"<" = "4"