[editor]
mouse = false
line-number = "relative"
cursorline = true
true-color = true
bufferline = "always"
color-modes = true

[editor.statusline]
left = [ "version-control" ]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "VISUAL"